spring:
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: bookstore
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 3000

